config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :recipes do
    member do
      patch 'toggle_public'
    end
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :foods do
    resources :inventory_foods
  end

  resources :inventories do
    get 'shopping_list', on: :member
    resources :inventory_foods
  end

  get '/public_recipes', to: 'recipes#public_index', as: 'public_recipes'

  # Additional routes...

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
end

app/controllers/recipes_controller.rb
# app/controllers/recipes_controller.rb

class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    # Load ingredients associated with the recipe
    @ingredients = @recipe.recipe_foods.includes(:food)
  end

  def toggle_public
    @recipe.toggle!(:public)
    redirect_to @recipe, notice: 'Recipe visibility toggled.'
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # GET /public_recipes
  def public_index
    @public_recipes_info = @public_recipes.map do |recipe|
      total_food_items = recipe.recipe_foods.sum(:quantity)
      total_price = recipe.recipe_foods.sum { |rf| rf.quantity * rf.food.price }

      {
        recipe:,
        user: recipe.user,
        total_food_items:,
        total_price:
      }
    end
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparationtime, :cookingtime, :description, :public, :user_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparationtime, style: "display: block" %>
    <%= form.number_field :preparationtime %>
  </div>

  <div>
    <%= form.label :cookingtime, style: "display: block" %>
    <%= form.number_field :cookingtime %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparationtime:</strong>
    <%= recipe.preparationtime %>
  </p>

  <p>
    <strong>Cookingtime:</strong>
    <%= recipe.cookingtime %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

  <p>
    <strong>User:</strong>
    <%= recipe.user_id %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="<%= dom_id inventory %>">
          <% @recipes.each do |recipe| %>
           <div>
              <span>
              <%= recipe.name %>
              <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
              </span>
              <span>
              <p>
              <%= recipe.description %>
              </p>
              </span>
           </div>
          <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/public_index.html.erb
<!-- app/views/recipes/public_index.html.erb -->
<h1>Public Recipes</h1>

<h2>Tier 1 Recipes (Food Items > 10)</h2>
<% @public_recipes.select { |recipe_info| recipe_info[:total_food_items] > 10 }.each do |recipe_info| %>
  <h3><%= recipe_info[:recipe].name %></h3>
  <p>By <%= recipe_info[:user].name %></p>
  <p>Total Food Items: <%= recipe_info[:total_food_items] %></p>
  <p>Total Price: <%= recipe_info[:total_price] %></p>
  <!-- Add more details as needed -->
<% end %>

<h2>Tier 2 Recipes (Food Items > 15)</h2>
<% @public_recipes.select { |recipe_info| recipe_info[:total_food_items] > 15 }.each do |recipe_info| %>
  <h3><%= recipe_info[:recipe].name %></h3>
  <p>By <%= recipe_info[:user].name %></p>
  <p>Total Food Items: <%= recipe_info[:total_food_items] %></p>
  <p>Total Price: <%= recipe_info[:total_price] %></p>
  <!-- Add more details as needed -->
<% end %>

<h2>Tier 3 Recipes (Food Items > 20)</h2>
<% @public_recipes.select { |recipe_info| recipe_info[:total_food_items] > 20 }.each do |recipe_info| %>
  <h3><%= recipe_info[:recipe].name %></h3>
  <p>By <%= recipe_info[:user].name %></p>
  <p>Total Food Items: <%= recipe_info[:total_food_items] %></p>
  <p>Total Price: <%= recipe_info[:total_price] %></p>
  <!-- Add more details as needed -->
<% end %>

app/views/recipes/show.html.erb
<!-- app/views/recipes/show.html.erb -->
<h1><%= @recipe.name %></h1>

<p>Prep Time: <%= @recipe.preparationtime %> minutes</p>
<p>Cooking Time: <%= @recipe.cookingtime %> minutes</p>

<h2>Steps</h2>
<%= simple_format(@recipe.description) %>

<h2>Public</h2>
<%= @recipe.public ? 'Public' : 'Private' %>
<%= link_to 'Toggle', toggle_public_recipe_path(@recipe), method: :patch %>

<h2>Ingredients</h2>
<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe.recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %></td>
        <td>
          <%= link_to 'Modify', edit_recipe_food_path(recipe_food) %>
          <%= link_to 'Remove', recipe_food, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%# POP-UP %>

<%= link_to 'Add Ingredient', new_recipe_food_path(@recipe), class: 'btn btn-primary' %>
<%= link_to 'Generate Shopping List', '#', id: 'generateShoppingListBtn' %>

<div id="shoppingListPopup" style="display: none;">
  <h2>Select Inventory</h2>
  <%= form_tag(generate_shopping_list_recipe_path(@recipe), method: :post, remote: true) do %>
    <div class="field">
      <%= label_tag 'inventory_id', 'Choose an Inventory:' %>
      <%= select_tag 'inventory_id', options_from_collection_for_select(current_user.inventories, 'id', 'name'), prompt: 'Select an Inventory' %>
    </div>
    <%= submit_tag 'Generate Shopping List' %>
  <% end %>
</div>

<%= link_to 'Back', recipes_path %>